package semantic

// Additional diagnostic policies preserve the specialized analyzers’ error order
// and recovery while shared signatures own all accepted types and counts.
func init() {
	for name, style := range map[string]builtinDiagnosticStyle{
		"inttostr":               {arityFormat: `There is no overloaded version of "IntToStr" that can be called with these arguments at %s`, silentMissingArguments: true, variantArityResult: true, argumentFormats: []string{"function 'IntToStr' expects Integer as first argument, got %s at %s", "function 'IntToStr' expects Integer as second argument (base), got %s at %s"}},
		"ord":                    {},
		"integer":                {name: "Ord"},
		"inttobin":               {optionalOr: true, argumentFormats: []string{"function 'IntToBin' expects Integer as first argument, got %s at %s", "function 'IntToBin' expects Integer as second argument, got %s at %s"}},
		"inttohex":               {optionalOr: true, argumentFormats: []string{"function 'IntToHex' expects Integer as first argument, got %s at %s", "function 'IntToHex' expects Integer as second argument, got %s at %s"}},
		"strtoint":               {optionalOr: true, argumentFormats: []string{"function 'StrToInt' expects String as first argument, got %s at %s", "function 'StrToInt' expects Integer as second argument (base), got %s at %s"}},
		"booltostr":              {argumentFormats: []string{"function 'BoolToStr' expects Boolean as argument, got %s at %s"}},
		"floattostr":             {optionalOr: true, argumentFormats: []string{"function 'FloatToStr' expects Float as argument, got %s at %s", "function 'FloatToStr' expects Integer precision as second argument, got %s at %s"}},
		"strtointdef":            {optionalOr: true, argumentFormats: []string{"function 'StrToIntDef' expects string as first argument, got %s at %s", "function 'StrToIntDef' expects integer as second argument, got %s at %s", "function 'StrToIntDef' expects Integer as third argument (base), got %s at %s"}},
		"strtofloatdef":          {argumentFormats: []string{"function 'StrToFloatDef' expects string as first argument, got %s at %s", "function 'StrToFloatDef' expects float as second argument, got %s at %s"}},
		"vartointdef":            {argumentFormats: []string{"", "function 'VarToIntDef' expects integer as second argument, got %s at %s"}},
		"vartofloatdef":          {argumentFormats: []string{"", "function 'VarToFloatDef' expects float as second argument, got %s at %s"}},
		"chr":                    {argumentFormats: []string{"function 'Chr' expects Integer as argument, got %s at %s"}},
		"substr":                 {optionalOr: true, argumentFormats: []string{"function 'SubStr' expects string as first argument, got %s at %s", "function 'SubStr' expects integer as second argument, got %s at %s", "function 'SubStr' expects integer as third argument, got %s at %s"}},
		"pos":                    {optionalOr: true, argumentFormats: []string{"function 'Pos' expects string as first argument, got %s at %s", "function 'Pos' expects string as second argument, got %s at %s", "function 'Pos' expects integer as third argument, got %s at %s"}},
		"trim":                   {optionalOr: true, argumentFormats: []string{"function 'Trim' expects string as first argument, got %s at %s", "function 'Trim' expects integer as second argument, got %s at %s", "function 'Trim' expects integer as third argument, got %s at %s"}},
		"trimleft":               {optionalOr: true, argumentFormats: []string{"function 'TrimLeft' expects string as first argument, got %s at %s", "function 'TrimLeft' expects integer as second argument, got %s at %s"}},
		"trimright":              {optionalOr: true, argumentFormats: []string{"function 'TrimRight' expects string as first argument, got %s at %s", "function 'TrimRight' expects integer as second argument, got %s at %s"}},
		"stringreplace":          {optionalOr: true, argumentFormats: []string{"function 'StringReplace' expects string as first argument, got %s at %s", "function 'StringReplace' expects string as second argument, got %s at %s", "function 'StringReplace' expects string as third argument, got %s at %s", "function 'StringReplace' expects integer as fourth argument, got %s at %s"}},
		"strreplace":             {name: "StringReplace", optionalOr: true, argumentFormats: []string{"function 'StringReplace' expects string as first argument, got %s at %s", "function 'StringReplace' expects string as second argument, got %s at %s", "function 'StringReplace' expects string as third argument, got %s at %s", "function 'StringReplace' expects integer as fourth argument, got %s at %s"}},
		"strreplacemacros":       {argumentFormats: []string{"function 'StrReplaceMacros' expects string as first argument, got %s at %s", "function 'StrReplaceMacros' expects array of String as second argument, got %s at %s", "function 'StrReplaceMacros' expects string as third argument, got %s at %s", "function 'StrReplaceMacros' expects string as fourth argument, got %s at %s"}},
		"substring":              {argumentFormats: []string{"function 'SubString' expects string as first argument, got %s at %s", "function 'SubString' expects integer as second argument, got %s at %s", "function 'SubString' expects integer as third argument, got %s at %s"}},
		"leftstr":                {argumentFormats: []string{"function 'LeftStr' expects string as first argument, got %s at %s", "function 'LeftStr' expects integer as second argument, got %s at %s"}},
		"midstr":                 {name: "SubStr", optionalOr: true, argumentFormats: []string{"function 'SubStr' expects string as first argument, got %s at %s", "function 'SubStr' expects integer as second argument, got %s at %s", "function 'SubStr' expects integer as third argument, got %s at %s"}},
		"strfind":                {optionalOr: true, argumentFormats: []string{"function 'StrFind' expects string as first argument, got %s at %s", "function 'StrFind' expects string as second argument, got %s at %s", "function 'StrFind' expects integer as third argument, got %s at %s"}},
		"strsplit":               {argumentFormats: []string{"function 'StrSplit' expects string as first argument, got %s at %s", "function 'StrSplit' expects string as second argument, got %s at %s"}},
		"strjoin":                {arrayElementFormat: "function 'StrJoin' expects array of string, got array of %s at %s", argumentFormats: []string{"function 'StrJoin' expects array as first argument, got %s at %s", "function 'StrJoin' expects string as second argument, got %s at %s"}},
		"strarraypack":           {arrayElementFormat: "function 'StrArrayPack' expects array of string, got array of %s at %s", argumentFormats: []string{"function 'StrArrayPack' expects array as argument, got %s at %s"}},
		"finddelimiter":          {optionalOr: true, argumentFormats: []string{"function 'FindDelimiter' expects string as first argument, got %s at %s", "function 'FindDelimiter' expects string as second argument, got %s at %s", "function 'FindDelimiter' expects integer as third argument, got %s at %s"}},
		"comparelocalestr":       {argumentFormats: []string{"function 'CompareLocaleStr' expects string as first argument, got %s at %s", "function 'CompareLocaleStr' expects string as second argument, got %s at %s", "function 'CompareLocaleStr' expects string as third argument, got %s at %s", "function 'CompareLocaleStr' expects boolean as fourth argument, got %s at %s"}},
		"strtoxml":               {optionalOr: true, argumentFormats: []string{"function 'StrToXML' expects String as first argument, got %s at %s", "function 'StrToXML' expects Integer as second argument (mode), got %s at %s"}},
		"clampint":               {groupFormat: "function 'ClampInt' expects Integer arguments, got %s, %s, %s at %s", analyzeAllFirst: true},
		"clamp":                  {groupFormat: "function 'Clamp' expects Integer or Float arguments, got %s, %s, %s at %s", analyzeAllFirst: true},
		"maxint":                 {argumentFormats: []string{"function 'MaxInt' expects Integer arguments, got %s at argument {index} at %s"}},
		"minint":                 {argumentFormats: []string{"function 'MinInt' expects Integer arguments, got %s at argument {index} at %s"}},
		"power":                  {groupFormat: "function 'Power' expects Integer or Float arguments, got %s and %s at %s", analyzeAllFirst: true},
		"arctan2":                {argumentFormats: []string{"function 'ArcTan2' expects Integer or Float as first argument, got %s at %s", "function 'ArcTan2' expects Integer or Float as second argument, got %s at %s"}, analyzeAllFirst: true},
		"hypot":                  {argumentFormats: []string{"function 'Hypot' expects Integer or Float as first argument, got %s at %s", "function 'Hypot' expects Integer or Float as second argument, got %s at %s"}, analyzeAllFirst: true},
		"randomize":              {noArguments: true, nilProcedureResult: true},
		"setrandseed":            {argumentFormats: []string{"function 'SetRandSeed' expects Integer, got %s at %s"}, nilProcedureResult: true},
		"isnan":                  {},
		"logn":                   {argumentFormats: []string{"function 'LogN' expects Float or Integer as first argument, got %s at %s", "function 'LogN' expects Float or Integer as second argument, got %s at %s"}},
		"sign":                   {argumentFormats: []string{"function 'Sign' expects Float or Integer, got %s at %s"}},
		"intpower":               {argumentFormats: []string{"function 'IntPower' expects Float or Integer as first argument, got %s at %s", "function 'IntPower' expects Integer as second argument, got %s at %s"}},
		"randg":                  {noArguments: true},
		"gcd":                    {argumentFormats: []string{"function 'Gcd' expects Integer as first argument, got %s at %s", "function 'Gcd' expects Integer as second argument, got %s at %s"}, analyzeAllFirst: true},
		"lcm":                    {argumentFormats: []string{"function 'Lcm' expects Integer as first argument, got %s at %s", "function 'Lcm' expects Integer as second argument, got %s at %s"}, analyzeAllFirst: true},
		"testbit":                {argumentFormats: []string{"function 'TestBit' expects Integer as first argument, got %s at %s", "function 'TestBit' expects Integer as second argument, got %s at %s"}, analyzeAllFirst: true},
		"haversine":              {argumentFormats: []string{"function 'Haversine' expects numeric argument {index}, got %s at %s"}},
		"comparenum":             {argumentFormats: []string{"function 'CompareNum' expects numeric first argument, got %s at %s", "function 'CompareNum' expects numeric second argument, got %s at %s"}, analyzeAllFirst: true},
		"round":                  {argumentFormats: []string{"function 'Round' expects Integer, Float, or Variant as argument, got %s at %s"}},
		"encodedate":             {aritySuffix: " (year, month, day)", argumentFormats: []string{"function 'EncodeDate' expects Integer as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"encodetime":             {aritySuffix: " (hour, minute, second, msec)", argumentFormats: []string{"function 'EncodeTime' expects Integer as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"encodedatetime":         {argumentFormats: []string{"function 'EncodeDateTime' expects Integer as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"yearof":                 {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'YearOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"monthof":                {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'MonthOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"dayof":                  {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DayOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"hourof":                 {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'HourOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"minuteof":               {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'MinuteOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"secondof":               {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'SecondOf' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"dayofweek":              {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DayOfWeek' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"dayoftheweek":           {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DayOfTheWeek' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"dayofyear":              {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DayOfYear' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"weeknumber":             {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'WeekNumber' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"yearofweek":             {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'YearOfWeek' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"formatdatetime":         {aritySuffix: " (format, dt)", argumentFormats: []string{"function 'FormatDateTime' expects String as first argument, got %s at %s", "function 'FormatDateTime' expects Float/TDateTime as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetimetostr":          {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateTimeToStr' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetostr":              {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateToStr' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"timetostr":              {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'TimeToStr' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetoiso8601":          {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateToISO8601' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetimetoiso8601":      {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateTimeToISO8601' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetimetorfc822":       {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateTimeToRFC822' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"strtodate":              {aritySuffix: " (String)", argumentFormats: []string{"function 'StrToDate' expects String, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"strtodatetime":          {aritySuffix: " (String)", argumentFormats: []string{"function 'StrToDateTime' expects String, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"strtotime":              {aritySuffix: " (String)", argumentFormats: []string{"function 'StrToTime' expects String, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"iso8601todatetime":      {aritySuffix: " (String)", argumentFormats: []string{"function 'ISO8601ToDateTime' expects String, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"rfc822todatetime":       {aritySuffix: " (String)", argumentFormats: []string{"function 'RFC822ToDateTime' expects String, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"incyear":                {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncYear' expects Float/TDateTime as first argument, got %s at %s", "function 'IncYear' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"incmonth":               {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncMonth' expects Float/TDateTime as first argument, got %s at %s", "function 'IncMonth' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"incday":                 {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncDay' expects Float/TDateTime as first argument, got %s at %s", "function 'IncDay' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"inchour":                {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncHour' expects Float/TDateTime as first argument, got %s at %s", "function 'IncHour' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"incminute":              {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncMinute' expects Float/TDateTime as first argument, got %s at %s", "function 'IncMinute' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"incsecond":              {aritySuffix: " (dt, amount)", argumentFormats: []string{"function 'IncSecond' expects Float/TDateTime as first argument, got %s at %s", "function 'IncSecond' expects Integer as second argument, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"daysbetween":            {aritySuffix: " (dt1, dt2)", argumentFormats: []string{"function 'DaysBetween' expects Float/TDateTime as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"hoursbetween":           {aritySuffix: " (dt1, dt2)", argumentFormats: []string{"function 'HoursBetween' expects Float/TDateTime as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"minutesbetween":         {aritySuffix: " (dt1, dt2)", argumentFormats: []string{"function 'MinutesBetween' expects Float/TDateTime as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"secondsbetween":         {aritySuffix: " (dt1, dt2)", argumentFormats: []string{"function 'SecondsBetween' expects Float/TDateTime as argument {index}, got %s at %s"}, arityRecovery: recoverAllArguments},
		"isleapyear":             {aritySuffix: " (year)", argumentFormats: []string{"function 'IsLeapYear' expects Integer, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"firstdayofyear":         {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'FirstDayOfYear' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"firstdayofnextyear":     {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'FirstDayOfNextYear' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"firstdayofmonth":        {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'FirstDayOfMonth' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"firstdayofnextmonth":    {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'FirstDayOfNextMonth' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"firstdayofweek":         {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'FirstDayOfWeek' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"unixtimetodatetime":     {aritySuffix: " (unixTime)", argumentFormats: []string{"function 'UnixTimeToDateTime' expects Integer, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"unixtimemsectodatetime": {aritySuffix: " (unixTime)", argumentFormats: []string{"function 'UnixTimeMSecToDateTime' expects Integer, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetimetounixtime":     {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateTimeToUnixTime' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"datetimetounixtimemsec": {aritySuffix: " (TDateTime)", argumentFormats: []string{"function 'DateTimeToUnixTimeMSec' expects Float/TDateTime, got %s at %s"}, arityRecovery: recoverDeclaredArguments},
		"parsejson":              {argumentFormats: []string{"ParseJSON expects String argument, got %s at %s"}},
		"tojsonformatted":        {optionalOr: true, argumentFormats: []string{"", "ToJSONFormatted expects Integer as second argument, got %s at %s"}},
		"jsonhasfield":           {argumentFormats: []string{"", "JSONHasField expects String as second argument, got %s at %s"}},
		"jsonkeys":               {},
		"jsonvalues":             {},
		"varisnull":              {argumentFormats: []string{"function 'VarIsNull' expects Variant argument, got %s at %s"}},
		"varisempty":             {argumentFormats: []string{"function 'VarIsEmpty' expects Variant argument, got %s at %s"}},
		"varisclear":             {argumentFormats: []string{"function 'VarIsClear' expects Variant argument, got %s at %s"}},
		"varisarray":             {argumentFormats: []string{"function 'VarIsArray' expects Variant argument, got %s at %s"}},
		"varisstr":               {argumentFormats: []string{"function 'VarIsStr' expects Variant argument, got %s at %s"}},
		"varisnumeric":           {argumentFormats: []string{"function 'VarIsNumeric' expects Variant argument, got %s at %s"}},
		"vartoint":               {argumentFormats: []string{"function 'VarToInt' expects Variant argument, got %s at %s"}},
		"vartofloat":             {argumentFormats: []string{"function 'VarToFloat' expects Variant argument, got %s at %s"}},
		"varastype":              {argumentFormats: []string{"function 'VarAsType' expects Variant argument, got %s at %s", "VarAsType type code must be Integer or String, got %s at %s"}},
	} {
		builtinDiagnosticStyles[name] = style
	}
}
