name: Deploy Playground to GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - playground/**
      - build/wasm/**
      - pkg/wasm/**
      - cmd/dwscript-wasm/**
      - internal/**
      - .github/workflows/deploy-playground.yml
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install just
        run: |
          curl --proto '=https' --tlsv1.2 -sSf https://just.systems/install.sh | bash -s -- --to /usr/local/bin

      - name: Build WASM
        run: just wasm

      - name: Prepare deployment
        run: |
          mkdir -p _site
          # Copy playground files (excluding the wasm symlink)
          cp -r playground/* _site/
          # Remove the symlink if it exists
          rm -f _site/wasm
          # Copy the actual WASM files
          mkdir -p _site/wasm
          cp -r build/wasm/dist/* _site/wasm/
          # Create a simple index redirect if needed
          if [ ! -f "_site/index.html" ]; then
            cat > _site/index.html <<EOF
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=index.html">
          </head>
          <body>
            <p>Redirecting to <a href="index.html">DWScript Playground</a>...</p>
          </body>
          </html>
          EOF
          fi

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
